version: '3.9'

services:
  redis:
      build: ./redis
      ports:
      - "6379:6379"
  app:
      build: .
      working_dir: /app
      ports:
      - "3000:3000"
      volumes:
      - .:/usr/local/etc/redis/volumes
      links:
      - redis
  